apiVersion: v1
kind: Service
metadata:
    name: "dechowdemocluster-e228"
    labels:
        app: "dechowdemocluster-e228"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dechowdemocluster-e228"